version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: websofiabou-db
    restart: always
    environment:
      - POSTGRES_DB=bd-websofiabou
      - POSTGRES_USER=fco-websofiabou
      - POSTGRES_PASSWORD=t9AWyMXGauynSI4B58I6
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema-init.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - websofiabou-net

  app:
    build: .
    container_name: websofiabou
    restart: always
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - DB_HOST=db
      - DB_NAME=bd-websofiabou
      - DB_USER=fco-websofiabou
      - DB_PASSWORD=t9AWyMXGauynSI4B58I6
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - websofiabou-net

volumes:
  pgdata:

networks:
  websofiabou-net:
    driver: bridge
